apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/Detroit
        image: linuxserver/tautulli
        name: tautulli
        ports:
        - containerPort: 8181
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tatulli-data