apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tatulli-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-noreplica
  resources:
    requests:
      storage: 9Gi
