apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tatulli-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: tatulli
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: tatulli-pv
