apiVersion: v1
kind: Service
metadata:
  labels:
    app: tautulli
    kubernetes.io/name: tautulli
  name: tautulli
  namespace: default
spec:
  ports:
  - name: tautulli
    port: 80
    protocol: TCP
    targetPort: 8181
  selector:
    app: tautulli
  type: LoadBalancer