apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: resilio
  name: resilio-pv
  namespace: resilio
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /volume1/Media/containerdata/resilio
    server: 10.0.0.20
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: resilio
  name: resilio-media
  namespace: resilio
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Ti
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /volume1/Media/
    server: 10.0.0.20
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: resilio
  name: resilio-sync
  namespace: resilio
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Ti
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /volume1/Sync/
    server: 10.0.0.20
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem