apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-data
  namespace: resilio
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: resilio
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: resilio-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-media
  namespace: resilio
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      name: resilio-media
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: resilio-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-sync
  namespace: resilio
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      name: resilio-sync
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: resilio-sync