apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitwarden
    kubernetes.io/name: bitwarden
  name: bitwarden
  namespace: bitwarden
spec:
  ports:
  - name: bitwarden
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bitwarden
  type: LoadBalancer
