apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: traefik
  name: traefik-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: traefik-data
    namespace: default
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /volume1/Media/containerdata/traefik
    server: 10.0.0.20
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  volumeMode: Filesystem
