apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      app: traefik
  storageClassName: longhorn
