apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: traefik
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: traefik-data
