apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    nodePort: 80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: admin
    nodePort: 30008
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: websecure
    nodePort: 443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: traefik
  type: NodePort
