apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  ports:
  - name: web
    nodePort: 30403
    port: 80
    protocol: TCP
    targetPort: web
  - name: admin
    nodePort: 30404
    port: 8080
    protocol: TCP
    targetPort: traefik
  - name: websecure
    nodePort: 30955
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  type: LoadBalancer
