apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: grocy
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: grocy-pv
