apiVersion: v1
kind: Service
metadata:
  labels:
    app: searx
    kubernetes.io/name: searx
  name: searx
  namespace: default
spec:
  ports:
  - name: searx
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: searx
  type: LoadBalancer