apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
    kubernetes.io/name: jellyfin
  name: jellyfin
  namespace: default
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8096
  selector:
    app: jellyfin
  type: LoadBalancer
