apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-noreplica
  resources:
    requests:
      storage: 20Gi