apiVersion: v1
kind: Service
metadata:
  name: mysql-mysql
  namespace: default
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  type: LoadBalancer
  loadBalancerIP: 10.0.202.30