apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freshrss
  name: freshrss
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  strategy: {}
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/Detroit
        image: ghcr.io/linuxserver/freshrss
        name: freshrss
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          limits:
              cpu: 100m
              memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: freshrss-data