apiVersion: v1
kind: Service
metadata:
  labels:
    app: freshrss
    kubernetes.io/name: freshrss
  name: freshrss
  namespace: default
spec:
  ports:
  - name: freshrss
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: freshrss
  type: LoadBalancer