apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wireguard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      securityContext:
        capabilities:
          add:
          - SYS_MODULE
          - NET_ADMIN
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/Detroit
        - name: PEERS
          value: "3"
        - name: SERVERURL
          value: vpn.cloud.martinojones.com
        image: linuxserver/wireguard
        imagePullPolicy: Always
        name: wireguard
        ports:
        - containerPort: 51820
          name: wireguard
          protocol: UDP
        volumeMounts:
        - mountPath: /config
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wireguard-data