apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-data
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: wireguard
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: wireguard-pv