apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: dizquetv
  name: dizquetv-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: dizquetv-data
    namespace: default
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /volume1/Media/containerdata/dizquetv
    server: 10.0.0.20
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
