apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dizquetv-data
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: dizquetv
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: dizquetv-pv